<?php

/**
 * This is the model base class for the table "publicacion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Publicacion".
 *
 * Columns in table "publicacion" available as properties of the model,
 * followed by relations of table "publicacion" available as properties of the model.
 *
 * @property integer $id
 * @property integer $controlseguimiento_id
 * @property string $fechaInicio
 * @property string $fechaCierre
 *
 * @property Controlseguimiento $controlseguimiento
 */
abstract class BasePublicacion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'publicacion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Publicacion|Publicacions', $n);
	}

	public static function representingColumn() {
		return 'fechaInicio';
	}

	public function rules() {
		return array(
			array('controlseguimiento_id', 'numerical', 'integerOnly'=>true),
			array('fechaInicio, fechaCierre', 'safe'),
			array('controlseguimiento_id, fechaInicio, fechaCierre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, controlseguimiento_id, fechaInicio, fechaCierre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'controlseguimiento' => array(self::BELONGS_TO, 'Controlseguimiento', 'controlseguimiento_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'controlseguimiento_id' => null,
			'fechaInicio' => Yii::t('app', 'Fecha Inicio'),
			'fechaCierre' => Yii::t('app', 'Fecha Cierre'),
			'controlseguimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('controlseguimiento_id', $this->controlseguimiento_id);
		$criteria->compare('fechaInicio', $this->fechaInicio, true);
		$criteria->compare('fechaCierre', $this->fechaCierre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}