<?php

/**
 * This is the model base class for the table "et".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Et".
 *
 * Columns in table "et" available as properties of the model,
 * followed by relations of table "et" available as properties of the model.
 *
 * @property integer $id
 * @property integer $procesocompra_id
 * @property integer $alerta_id
 * @property string $forma
 * @property string $fecha
 * @property string $observacion1
 * @property string $observacion2
 * @property integer $alerta
 * @property integer $alertal1
 *
 * @property Alerta $alerta0
 * @property Procesocompra $procesocompra
 */
abstract class BaseEt extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'et';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Et|Ets', $n);
	}

	public static function representingColumn() {
		return 'forma';
	}

	public function rules() {
		return array(
			array('procesocompra_id, alerta_id, alerta, alertal1', 'numerical', 'integerOnly'=>true),
			array('forma', 'length', 'max'=>45),
			array('observacion1, observacion2', 'length', 'max'=>100),
			array('fecha', 'safe'),
			array('procesocompra_id, alerta_id, forma, fecha, observacion1, observacion2, alerta, alertal1', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, procesocompra_id, alerta_id, forma, fecha, observacion1, observacion2, alerta, alertal1', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'alerta0' => array(self::BELONGS_TO, 'Alerta', 'alerta_id'),
			'procesocompra' => array(self::BELONGS_TO, 'Procesocompra', 'procesocompra_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'procesocompra_id' => null,
			'alerta_id' => null,
			'forma' => Yii::t('app', 'Forma'),
			'fecha' => Yii::t('app', 'Fecha'),
			'observacion1' => Yii::t('app', 'Observacion1'),
			'observacion2' => Yii::t('app', 'Observacion2'),
			'alerta' => Yii::t('app', 'Alerta'),
			'alertal1' => Yii::t('app', 'Alertal1'),
			'alerta0' => null,
			'procesocompra' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('procesocompra_id', $this->procesocompra_id);
		$criteria->compare('alerta_id', $this->alerta_id);
		$criteria->compare('forma', $this->forma, true);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('observacion1', $this->observacion1, true);
		$criteria->compare('observacion2', $this->observacion2, true);
		$criteria->compare('alerta', $this->alerta);
		$criteria->compare('alertal1', $this->alertal1);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}