<?php

/**
 * This is the model base class for the table "enviocontratofirma".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Enviocontratofirma".
 *
 * Columns in table "enviocontratofirma" available as properties of the model,
 * followed by relations of table "enviocontratofirma" available as properties of the model.
 *
 * @property integer $id
 * @property integer $controlseguimiento_id
 * @property string $fechaCreacion
 * @property string $estado
 * @property string $fechaProveedor
 * @property string $fechaFirmaContrato
 * @property string $observacion
 * @property integer $alerta
 *
 * @property Controlseguimiento $controlseguimiento
 */
abstract class BaseEnviocontratofirma extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'enviocontratofirma';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Enviocontratofirma|Enviocontratofirmas', $n);
	}

	public static function representingColumn() {
		return 'fechaCreacion';
	}

	public function rules() {
		return array(
			array('controlseguimiento_id, alerta', 'numerical', 'integerOnly'=>true),
			array('estado', 'length', 'max'=>45),
			array('observacion', 'length', 'max'=>200),
			array('fechaCreacion, fechaProveedor, fechaFirmaContrato', 'safe'),
			array('controlseguimiento_id, fechaCreacion, estado, fechaProveedor, fechaFirmaContrato, observacion, alerta', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, controlseguimiento_id, fechaCreacion, estado, fechaProveedor, fechaFirmaContrato, observacion, alerta', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'controlseguimiento' => array(self::BELONGS_TO, 'Controlseguimiento', 'controlseguimiento_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'controlseguimiento_id' => null,
			'fechaCreacion' => Yii::t('app', 'Fecha Creacion'),
			'estado' => Yii::t('app', 'Estado'),
			'fechaProveedor' => Yii::t('app', 'Fecha Proveedor'),
			'fechaFirmaContrato' => Yii::t('app', 'Fecha Firma Contrato'),
			'observacion' => Yii::t('app', 'Observacion'),
			'alerta' => Yii::t('app', 'Alerta'),
			'controlseguimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('controlseguimiento_id', $this->controlseguimiento_id);
		$criteria->compare('fechaCreacion', $this->fechaCreacion, true);
		$criteria->compare('estado', $this->estado, true);
		$criteria->compare('fechaProveedor', $this->fechaProveedor, true);
		$criteria->compare('fechaFirmaContrato', $this->fechaFirmaContrato, true);
		$criteria->compare('observacion', $this->observacion, true);
		$criteria->compare('alerta', $this->alerta);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}