<?php

/**
 * This is the model base class for the table "adquisicion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Adquisicion".
 *
 * Columns in table "adquisicion" available as properties of the model,
 * followed by relations of table "adquisicion" available as properties of the model.
 *
 * @property integer $id
 * @property integer $alerta_id
 * @property integer $procesocompra_id
 * @property string $estado
 * @property string $fechaCreacion
 * @property string $fechaRespuesta
 * @property string $observacion
 * @property integer $alerta
 *
 * @property Alerta $alerta0
 * @property Procesocompra $procesocompra
 */
abstract class BaseAdquisicion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'adquisicion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Adquisicion|Adquisicions', $n);
	}

	public static function representingColumn() {
		return 'estado';
	}

	public function rules() {
		return array(
			array('alerta_id, procesocompra_id, alerta', 'numerical', 'integerOnly'=>true),
			array('estado', 'length', 'max'=>45),
			array('observacion', 'length', 'max'=>200),
			array('fechaCreacion, fechaRespuesta', 'safe'),
			array('alerta_id, procesocompra_id, estado, fechaCreacion, fechaRespuesta, observacion, alerta', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, alerta_id, procesocompra_id, estado, fechaCreacion, fechaRespuesta, observacion, alerta', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'alerta0' => array(self::BELONGS_TO, 'Alerta', 'alerta_id'),
			'procesocompra' => array(self::BELONGS_TO, 'Procesocompra', 'procesocompra_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'alerta_id' => null,
			'procesocompra_id' => null,
			'estado' => Yii::t('app', 'Estado'),
			'fechaCreacion' => Yii::t('app', 'Fecha Creacion'),
			'fechaRespuesta' => Yii::t('app', 'Fecha Respuesta'),
			'observacion' => Yii::t('app', 'Observacion'),
			'alerta' => Yii::t('app', 'Alerta'),
			'alerta0' => null,
			'procesocompra' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('alerta_id', $this->alerta_id);
		$criteria->compare('procesocompra_id', $this->procesocompra_id);
		$criteria->compare('estado', $this->estado, true);
		$criteria->compare('fechaCreacion', $this->fechaCreacion, true);
		$criteria->compare('fechaRespuesta', $this->fechaRespuesta, true);
		$criteria->compare('observacion', $this->observacion, true);
		$criteria->compare('alerta', $this->alerta);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}