<?php

/**
 * This is the model base class for the table "recopilacioninfo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Recopilacioninfo".
 *
 * Columns in table "recopilacioninfo" available as properties of the model,
 * followed by relations of table "recopilacioninfo" available as properties of the model.
 *
 * @property integer $id
 * @property integer $controlseguimiento_id
 * @property string $fase
 * @property string $fecha1
 * @property string $fecha2
 * @property string $observacion
 *
 * @property Controlseguimiento $controlseguimiento
 */
abstract class BaseRecopilacioninfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'recopilacioninfo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Recopilacioninfo|Recopilacioninfos', $n);
	}

	public static function representingColumn() {
		return 'fase';
	}

	public function rules() {
		return array(
			array('controlseguimiento_id', 'numerical', 'integerOnly'=>true),
			array('fase', 'length', 'max'=>45),
			array('observacion', 'length', 'max'=>200),
			array('fecha1, fecha2', 'safe'),
			array('controlseguimiento_id, fase, fecha1, fecha2, observacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, controlseguimiento_id, fase, fecha1, fecha2, observacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'controlseguimiento' => array(self::BELONGS_TO, 'Controlseguimiento', 'controlseguimiento_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'controlseguimiento_id' => null,
			'fase' => Yii::t('app', 'Fase'),
			'fecha1' => Yii::t('app', 'Fecha1'),
			'fecha2' => Yii::t('app', 'Fecha2'),
			'observacion' => Yii::t('app', 'Observacion'),
			'controlseguimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('controlseguimiento_id', $this->controlseguimiento_id);
		$criteria->compare('fase', $this->fase, true);
		$criteria->compare('fecha1', $this->fecha1, true);
		$criteria->compare('fecha2', $this->fecha2, true);
		$criteria->compare('observacion', $this->observacion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}