<?php

/**
 * This is the model base class for the table "controlseguimiento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Controlseguimiento".
 *
 * Columns in table "controlseguimiento" available as properties of the model,
 * followed by relations of table "controlseguimiento" available as properties of the model.
 *
 * @property integer $id
 * @property integer $procesocompra_id
 * @property string $tipo
 *
 * @property Abogadasecretaria[] $abogadasecretarias
 * @property Adjudicacion[] $adjudicacions
 * @property Aj[] $ajs
 * @property Asesorjuridico[] $asesorjuridicos
 * @property Comisionevaluacion[] $comisionevaluacions
 * @property Contraloria[] $contralorias
 * @property Procesocompra $procesocompra
 * @property Directorproyecto[] $directorproyectos
 * @property Envinformeseva[] $envinformesevas
 * @property Enviocontratofirma[] $enviocontratofirmas
 * @property Oficioconductor[] $oficioconductors
 * @property Procesoevaluacion[] $procesoevaluacions
 * @property Publicacion[] $publicacions
 * @property Recinformacionsup[] $recinformacionsups
 * @property Recopilacioninfo[] $recopilacioninfos
 * @property Resofcontrato[] $resofcontratos
 * @property Resofcontratovaf[] $resofcontratovafs
 * @property Resolucionadlp[] $resolucionadlps
 * @property Resolucionadodes[] $resolucionadodes
 * @property Resolucionof[] $resolucionofs
 * @property Resolucionoficializada[] $resolucionoficializadas
 * @property Secretaria[] $secretarias
 * @property Vaf[] $vafs
 */
abstract class BaseControlseguimiento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'controlseguimiento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Controlseguimiento|Controlseguimientos', $n);
	}

	public static function representingColumn() {
		return 'tipo';
	}

	public function rules() {
		return array(
			array('procesocompra_id', 'numerical', 'integerOnly'=>true),
			array('tipo', 'length', 'max'=>45),
			array('procesocompra_id, tipo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, procesocompra_id, tipo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'abogadasecretarias' => array(self::HAS_MANY, 'Abogadasecretaria', 'controlseguimiento_id'),
			'adjudicacions' => array(self::HAS_MANY, 'Adjudicacion', 'controlseguimiento_id'),
			'ajs' => array(self::HAS_MANY, 'Aj', 'controlseguimiento_id'),
			'asesorjuridicos' => array(self::HAS_MANY, 'Asesorjuridico', 'controlseguimiento_id'),
			'comisionevaluacions' => array(self::HAS_MANY, 'Comisionevaluacion', 'controlseguimiento_id'),
			'contralorias' => array(self::HAS_MANY, 'Contraloria', 'controlseguimiento_id'),
			'procesocompra' => array(self::BELONGS_TO, 'Procesocompra', 'procesocompra_id'),
			'directorproyectos' => array(self::HAS_MANY, 'Directorproyecto', 'controlseguimiento_id'),
			'envinformesevas' => array(self::HAS_MANY, 'Envinformeseva', 'controlseguimiento_id'),
			'enviocontratofirmas' => array(self::HAS_MANY, 'Enviocontratofirma', 'controlseguimiento_id'),
			'plantillas' => array(self::HAS_MANY, 'Plantilla', 'controlseguimiento_id'),
			'oficioconductors' => array(self::HAS_MANY, 'Oficioconductor', 'controlseguimiento_id'),
			'procesoevaluacions' => array(self::HAS_MANY, 'Procesoevaluacion', 'controlseguimiento_id'),
			'publicacions' => array(self::HAS_MANY, 'Publicacion', 'controlseguimiento_id'),
			'recinformacionsups' => array(self::HAS_MANY, 'Recinformacionsup', 'controlseguimiento_id'),
			'recopilacioninfos' => array(self::HAS_MANY, 'Recopilacioninfo', 'controlseguimiento_id'),
			'resofcontratos' => array(self::HAS_MANY, 'Resofcontrato', 'controlseguimiento_id'),
			'resofcontratovafs' => array(self::HAS_MANY, 'Resofcontratovaf', 'controlseguimiento_id'),
			'resolucionadlps' => array(self::HAS_MANY, 'Resolucionadlp', 'controlseguimiento_id'),
			'resolucionadodes' => array(self::HAS_MANY, 'Resolucionadodes', 'controlseguimiento_id'),
			'resolucionofs' => array(self::HAS_MANY, 'Resolucionof', 'controlseguimiento_id'),
			'resolucionoficializadas' => array(self::HAS_MANY, 'Resolucionoficializada', 'controlseguimiento_id'),
			'secretarias' => array(self::HAS_MANY, 'Secretaria', 'controlseguimiento_id'),
			'vafs' => array(self::HAS_MANY, 'Vaf', 'controlseguimiento_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'procesocompra_id' => null,
			'tipo' => Yii::t('app', 'Tipo'),
			'abogadasecretarias' => null,
			'adjudicacions' => null,
			'ajs' => null,
			'asesorjuridicos' => null,
			'comisionevaluacions' => null,
			'contralorias' => null,
			'procesocompra' => null,
			'directorproyectos' => null,
			'envinformesevas' => null,
			'enviocontratofirmas' => null,
			'oficioconductors' => null,
			'plantillas' => null,
			'procesoevaluacions' => null,
			'publicacions' => null,
			'recinformacionsups' => null,
			'recopilacioninfos' => null,
			'resofcontratos' => null,
			'resofcontratovafs' => null,
			'resolucionadlps' => null,
			'resolucionadodes' => null,
			'resolucionofs' => null,
			'resolucionoficializadas' => null,
			'secretarias' => null,
			'vafs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('procesocompra_id', $this->procesocompra_id);
		$criteria->compare('tipo', $this->tipo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}