<?php

/**
 * This is the model base class for the table "vaf".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Vaf".
 *
 * Columns in table "vaf" available as properties of the model,
 * followed by relations of table "vaf" available as properties of the model.
 *
 * @property integer $id
 * @property integer $controlseguimiento_id
 * @property string $numResolucion
 * @property string $fechaCreacion
 * @property string $fechaRespuesta
 * @property integer $alerta
 *
 * @property Controlseguimiento $controlseguimiento
 */
abstract class BaseVaf extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vaf';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Vaf|Vafs', $n);
	}

	public static function representingColumn() {
		return 'numResolucion';
	}

	public function rules() {
		return array(
			array('controlseguimiento_id, alerta', 'numerical', 'integerOnly'=>true),
			array('numResolucion', 'length', 'max'=>45),
			array('fechaCreacion, fechaRespuesta', 'safe'),
			array('controlseguimiento_id, numResolucion, fechaCreacion, fechaRespuesta, alerta', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, controlseguimiento_id, numResolucion, fechaCreacion, fechaRespuesta, alerta', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'controlseguimiento' => array(self::BELONGS_TO, 'Controlseguimiento', 'controlseguimiento_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'controlseguimiento_id' => null,
			'numResolucion' => Yii::t('app', 'Num Resolucion'),
			'fechaCreacion' => Yii::t('app', 'Fecha Creacion'),
			'fechaRespuesta' => Yii::t('app', 'Fecha Respuesta'),
			'alerta' => Yii::t('app', 'Alerta'),
			'controlseguimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('controlseguimiento_id', $this->controlseguimiento_id);
		$criteria->compare('numResolucion', $this->numResolucion, true);
		$criteria->compare('fechaCreacion', $this->fechaCreacion, true);
		$criteria->compare('fechaRespuesta', $this->fechaRespuesta, true);
		$criteria->compare('alerta', $this->alerta);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}