<?php

/**
 * This is the model base class for the table "plantilla".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Plantilla".
 *
 * Columns in table "plantilla" available as properties of the model,
 * followed by relations of table "plantilla" available as properties of the model.
 *
 * @property integer $id
 * @property integer $procesogasto_id
 * @property integer $proyecto_id
 * @property string $item
 * @property string $numDocumentoSC
 * @property string $fechaSC
 * @property string $numDocumentoOC
 * @property string $fechaOC
 * @property string $tipoDocumentoDP
 * @property string $numDocumentoDP
 * @property string $fechaDP
 * @property string $numComprobanteEI
 * @property string $fechaEI
 * @property integer $numOrdenPagoEI
 * @property string $tipoDocumentoFB
 * @property string $numDocumentoFB
 * @property string $rutProveedorFB
 * @property string $fechaFB
 * @property string $fechaCancelacionFB
 * @property string $detalleDocumentoFB
 * @property string $valorCanceladoFB
 * @property string $observacion1FB
 * @property string $procesosFB
 *
 * @property Procesogasto $procesogasto
 * @property Proyecto $proyecto
 */
abstract class BasePlantilla extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'plantilla';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Plantilla|Plantillas', $n);
	}

	public static function representingColumn() {
		return 'item';
	}

	public function rules() {
		return array(
			array('procesogasto_id, proyecto_id, numOrdenPagoEI', 'numerical', 'integerOnly'=>true),
			array('item, numDocumentoSC, numDocumentoOC, tipoDocumentoDP, numDocumentoDP, numComprobanteEI, tipoDocumentoFB, numDocumentoFB, rutProveedorFB, valorCanceladoFB', 'length', 'max'=>45),
			array('detalleDocumentoFB, observacion1FB, procesosFB', 'length', 'max'=>200),
			array('fechaSC, fechaOC, fechaDP, fechaEI, fechaFB, fechaCancelacionFB', 'safe'),
			array('procesogasto_id, proyecto_id, item, numDocumentoSC, fechaSC, numDocumentoOC, fechaOC, tipoDocumentoDP, numDocumentoDP, fechaDP, numComprobanteEI, fechaEI, numOrdenPagoEI, tipoDocumentoFB, numDocumentoFB, rutProveedorFB, fechaFB, fechaCancelacionFB, detalleDocumentoFB, valorCanceladoFB, observacion1FB, procesosFB', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, procesogasto_id, proyecto_id, item, numDocumentoSC, fechaSC, numDocumentoOC, fechaOC, tipoDocumentoDP, numDocumentoDP, fechaDP, numComprobanteEI, fechaEI, numOrdenPagoEI, tipoDocumentoFB, numDocumentoFB, rutProveedorFB, fechaFB, fechaCancelacionFB, detalleDocumentoFB, valorCanceladoFB, observacion1FB, procesosFB', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'procesogasto' => array(self::BELONGS_TO, 'Procesogasto', 'procesogasto_id'),
			'proyecto' => array(self::BELONGS_TO, 'Proyecto', 'proyecto_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'procesogasto_id' => null,
			'proyecto_id' => null,
			'item' => Yii::t('app', 'Item'),
			'numDocumentoSC' => Yii::t('app', 'Num Documento Sc'),
			'fechaSC' => Yii::t('app', 'Fecha Sc'),
			'numDocumentoOC' => Yii::t('app', 'Num Documento Oc'),
			'fechaOC' => Yii::t('app', 'Fecha Oc'),
			'tipoDocumentoDP' => Yii::t('app', 'Tipo Documento Dp'),
			'numDocumentoDP' => Yii::t('app', 'Num Documento Dp'),
			'fechaDP' => Yii::t('app', 'Fecha Dp'),
			'numComprobanteEI' => Yii::t('app', 'Num Comprobante Ei'),
			'fechaEI' => Yii::t('app', 'Fecha Ei'),
			'numOrdenPagoEI' => Yii::t('app', 'Num Orden Pago Ei'),
			'tipoDocumentoFB' => Yii::t('app', 'Tipo Documento Fb'),
			'numDocumentoFB' => Yii::t('app', 'Num Documento Fb'),
			'rutProveedorFB' => Yii::t('app', 'Rut Proveedor Fb'),
			'fechaFB' => Yii::t('app', 'Fecha Fb'),
			'fechaCancelacionFB' => Yii::t('app', 'Fecha Cancelacion Fb'),
			'detalleDocumentoFB' => Yii::t('app', 'Detalle Documento Fb'),
			'valorCanceladoFB' => Yii::t('app', 'Valor Cancelado Fb'),
			'observacion1FB' => Yii::t('app', 'Observacion1 Fb'),
			'procesosFB' => Yii::t('app', 'Procesos Fb'),
			'procesogasto' => null,
			'proyecto' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('procesogasto_id', $this->procesogasto_id);
		$criteria->compare('proyecto_id', $this->proyecto_id);
		$criteria->compare('item', $this->item, true);
		$criteria->compare('numDocumentoSC', $this->numDocumentoSC, true);
		$criteria->compare('fechaSC', $this->fechaSC, true);
		$criteria->compare('numDocumentoOC', $this->numDocumentoOC, true);
		$criteria->compare('fechaOC', $this->fechaOC, true);
		$criteria->compare('tipoDocumentoDP', $this->tipoDocumentoDP, true);
		$criteria->compare('numDocumentoDP', $this->numDocumentoDP, true);
		$criteria->compare('fechaDP', $this->fechaDP, true);
		$criteria->compare('numComprobanteEI', $this->numComprobanteEI, true);
		$criteria->compare('fechaEI', $this->fechaEI, true);
		$criteria->compare('numOrdenPagoEI', $this->numOrdenPagoEI);
		$criteria->compare('tipoDocumentoFB', $this->tipoDocumentoFB, true);
		$criteria->compare('numDocumentoFB', $this->numDocumentoFB, true);
		$criteria->compare('rutProveedorFB', $this->rutProveedorFB, true);
		$criteria->compare('fechaFB', $this->fechaFB, true);
		$criteria->compare('fechaCancelacionFB', $this->fechaCancelacionFB, true);
		$criteria->compare('detalleDocumentoFB', $this->detalleDocumentoFB, true);
		$criteria->compare('valorCanceladoFB', $this->valorCanceladoFB, true);
		$criteria->compare('observacion1FB', $this->observacion1FB, true);
		$criteria->compare('procesosFB', $this->procesosFB, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}