<?php

/**
 * This is the model base class for the table "resolucionoficializada".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Resolucionoficializada".
 *
 * Columns in table "resolucionoficializada" available as properties of the model,
 * followed by relations of table "resolucionoficializada" available as properties of the model.
 *
 * @property integer $id
 * @property integer $controlseguimiento_id
 * @property string $fechaEnvioRes
 * @property string $observacion
 *
 * @property Controlseguimiento $controlseguimiento
 */
abstract class BaseResolucionoficializada extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'resolucionoficializada';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Resolucionoficializada|Resolucionoficializadas', $n);
	}

	public static function representingColumn() {
		return 'fechaEnvioRes';
	}

	public function rules() {
		return array(
			array('controlseguimiento_id', 'numerical', 'integerOnly'=>true),
			array('observacion', 'length', 'max'=>200),
			array('fechaEnvioRes', 'safe'),
			array('controlseguimiento_id, fechaEnvioRes, observacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, controlseguimiento_id, fechaEnvioRes, observacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'controlseguimiento' => array(self::BELONGS_TO, 'Controlseguimiento', 'controlseguimiento_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'controlseguimiento_id' => null,
			'fechaEnvioRes' => Yii::t('app', 'Fecha Envio Res'),
			'observacion' => Yii::t('app', 'Observacion'),
			'controlseguimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('controlseguimiento_id', $this->controlseguimiento_id);
		$criteria->compare('fechaEnvioRes', $this->fechaEnvioRes, true);
		$criteria->compare('observacion', $this->observacion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}