<?php

/**
 * This is the model base class for the table "resolucionadodes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Resolucionadodes".
 *
 * Columns in table "resolucionadodes" available as properties of the model,
 * followed by relations of table "resolucionadodes" available as properties of the model.
 *
 * @property integer $id
 * @property integer $controlseguimiento_id
 * @property string $tipo
 * @property string $fechaCreacion
 * @property string $numResolucion
 * @property string $firma
 * @property string $fechaRes
 * @property string $fechaFirma
 * @property string $actaAdodes
 * @property string $fechaActa
 * @property integer $alerta1
 * @property integer $alerta2
 *
 * @property Controlseguimiento $controlseguimiento
 */
abstract class BaseResolucionadodes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'resolucionadodes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Resolucionadodes|Resolucionadodes', $n);
	}

	public static function representingColumn() {
		return 'tipo';
	}

	public function rules() {
		return array(
			array('controlseguimiento_id, alerta1, alerta2', 'numerical', 'integerOnly'=>true),
			array('tipo, numResolucion, firma, actaAdodes', 'length', 'max'=>45),
			array('fechaCreacion, fechaRes, fechaFirma, fechaActa', 'safe'),
			array('controlseguimiento_id, tipo, fechaCreacion, numResolucion, firma, fechaRes, fechaFirma, actaAdodes, fechaActa, alerta1, alerta2', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, controlseguimiento_id, tipo, fechaCreacion, numResolucion, firma, fechaRes, fechaFirma, actaAdodes, fechaActa, alerta1, alerta2', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'controlseguimiento' => array(self::BELONGS_TO, 'Controlseguimiento', 'controlseguimiento_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'controlseguimiento_id' => null,
			'tipo' => Yii::t('app', 'Tipo'),
			'fechaCreacion' => Yii::t('app', 'Fecha Creacion'),
			'numResolucion' => Yii::t('app', 'Num Resolucion'),
			'firma' => Yii::t('app', 'Firma'),
			'fechaRes' => Yii::t('app', 'Fecha Res'),
			'fechaFirma' => Yii::t('app', 'Fecha Firma'),
			'actaAdodes' => Yii::t('app', 'Acta Adodes'),
			'fechaActa' => Yii::t('app', 'Fecha Acta'),
			'alerta1' => Yii::t('app', 'Alerta1'),
			'alerta2' => Yii::t('app', 'Alerta2'),
			'controlseguimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('controlseguimiento_id', $this->controlseguimiento_id);
		$criteria->compare('tipo', $this->tipo, true);
		$criteria->compare('fechaCreacion', $this->fechaCreacion, true);
		$criteria->compare('numResolucion', $this->numResolucion, true);
		$criteria->compare('firma', $this->firma, true);
		$criteria->compare('fechaRes', $this->fechaRes, true);
		$criteria->compare('fechaFirma', $this->fechaFirma, true);
		$criteria->compare('actaAdodes', $this->actaAdodes, true);
		$criteria->compare('fechaActa', $this->fechaActa, true);
		$criteria->compare('alerta1', $this->alerta1);
		$criteria->compare('alerta2', $this->alerta2);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}