<?php

/**
 * This is the model base class for the table "honorario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Honorario".
 *
 * Columns in table "honorario" available as properties of the model,
 * followed by relations of table "honorario" available as properties of the model.
 *
 * @property integer $id
 * @property integer $procesogasto_id
 * @property string $item
 * @property string $nombrePersona
 * @property string $rut
 * @property integer $numConvenio
 * @property string $fechaInicio
 * @property string $fechaTermino
 * @property integer $cuotas
 * @property string $monto
 * @property string $fechaRecilio
 * @property string $reciliacion
 *
 * @property Procesogasto $procesogasto
 */
abstract class BaseHonorario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'honorario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Honorario|Honorarios', $n);
	}

	public static function representingColumn() {
		return 'item';
	}

	public function rules() {
		return array(
			array('procesogasto_id, numConvenio, cuotas', 'numerical', 'integerOnly'=>true),
			array('item, rut, monto, reciliacion', 'length', 'max'=>45),
			array('nombrePersona', 'length', 'max'=>200),
			array('fechaInicio, fechaTermino, fechaRecilio', 'safe'),
			array('procesogasto_id, item, nombrePersona, rut, numConvenio, fechaInicio, fechaTermino, cuotas, monto, fechaRecilio, reciliacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, procesogasto_id, item, nombrePersona, rut, numConvenio, fechaInicio, fechaTermino, cuotas, monto, fechaRecilio, reciliacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'procesogasto' => array(self::BELONGS_TO, 'Procesogasto', 'procesogasto_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'procesogasto_id' => null,
			'item' => Yii::t('app', 'Item'),
			'nombrePersona' => Yii::t('app', 'Nombre Persona'),
			'rut' => Yii::t('app', 'Rut'),
			'numConvenio' => Yii::t('app', 'Num Convenio'),
			'fechaInicio' => Yii::t('app', 'Fecha Inicio'),
			'fechaTermino' => Yii::t('app', 'Fecha Termino'),
			'cuotas' => Yii::t('app', 'Cuotas'),
			'monto' => Yii::t('app', 'Monto'),
			'fechaRecilio' => Yii::t('app', 'Fecha Recilio'),
			'reciliacion' => Yii::t('app', 'Reciliacion'),
			'procesogasto' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('procesogasto_id', $this->procesogasto_id);
		$criteria->compare('item', $this->item, true);
		$criteria->compare('nombrePersona', $this->nombrePersona, true);
		$criteria->compare('rut', $this->rut, true);
		$criteria->compare('numConvenio', $this->numConvenio);
		$criteria->compare('fechaInicio', $this->fechaInicio, true);
		$criteria->compare('fechaTermino', $this->fechaTermino, true);
		$criteria->compare('cuotas', $this->cuotas);
		$criteria->compare('monto', $this->monto, true);
		$criteria->compare('fechaRecilio', $this->fechaRecilio, true);
		$criteria->compare('reciliacion', $this->reciliacion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}