<?php

/**
 * This is the model base class for the table "recinformacionsup".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Recinformacionsup".
 *
 * Columns in table "recinformacionsup" available as properties of the model,
 * followed by relations of table "recinformacionsup" available as properties of the model.
 *
 * @property integer $id
 * @property integer $controlseguimiento_id
 * @property string $fechaCreacion
 * @property string $boletayotros
 * @property string $fecha1
 * @property string $observacion
 * @property string $envioantecedentes
 * @property string $fecha2
 *
 * @property Controlseguimiento $controlseguimiento
 */
abstract class BaseRecinformacionsup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'recinformacionsup';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Recinformacionsup|Recinformacionsups', $n);
	}

	public static function representingColumn() {
		return 'fechaCreacion';
	}

	public function rules() {
		return array(
			array('controlseguimiento_id', 'numerical', 'integerOnly'=>true),
			array('boletayotros, observacion, envioantecedentes', 'length', 'max'=>200),
			array('fechaCreacion, fecha1, fecha2', 'safe'),
			array('controlseguimiento_id, fechaCreacion, boletayotros, fecha1, observacion, envioantecedentes, fecha2', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, controlseguimiento_id, fechaCreacion, boletayotros, fecha1, observacion, envioantecedentes, fecha2', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'controlseguimiento' => array(self::BELONGS_TO, 'Controlseguimiento', 'controlseguimiento_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'controlseguimiento_id' => null,
			'fechaCreacion' => Yii::t('app', 'Fecha Creacion'),
			'boletayotros' => Yii::t('app', 'Boletayotros'),
			'fecha1' => Yii::t('app', 'Fecha1'),
			'observacion' => Yii::t('app', 'Observacion'),
			'envioantecedentes' => Yii::t('app', 'Envioantecedentes'),
			'fecha2' => Yii::t('app', 'Fecha2'),
			'controlseguimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('controlseguimiento_id', $this->controlseguimiento_id);
		$criteria->compare('fechaCreacion', $this->fechaCreacion, true);
		$criteria->compare('boletayotros', $this->boletayotros, true);
		$criteria->compare('fecha1', $this->fecha1, true);
		$criteria->compare('observacion', $this->observacion, true);
		$criteria->compare('envioantecedentes', $this->envioantecedentes, true);
		$criteria->compare('fecha2', $this->fecha2, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}